### PR TITLE
Switches http and json libraries; adds streaming and file upload

### PR DESCRIPTION
**Pull request by noonian**

### CODE REVIEW

**Comment by bmabey** [comment]
Did you rebase to the latest master?  (It doesn't look like your commits apply cleanly.)

**Comment by noonian** [comment]
Ok, I merged your master into mine and fixed conflicts.

I tested the tweet functionality (new to my branch) and it worked great so I think everything is working with the async http client.

I had to re-write get-json and post-json a bit when I switched clients because http.async.client doesn't provide the request primitive that clj-http does.

**Comment by noonian** [comment]
Midje tests are failing because they haven't been updated to use http.async.client. I'm looking at it but I'm pretty new to midje (and clojure) and I'm not sure how to stub out the http methods.

**Comment by bmabey** [comment]
Cool, thanks for doing that.  I've merged in the changes and fixed the broken test.

**Comment by bmabey** [comment]
Just pushed `v2.2.0`.

**Comment by noonian** [comment]
Awesome, thanks!

**Pull request merged**
